

/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                             oData  V3                                     /////////
//////////////////////////////////////////////////////////////////////////////////////*/
(function(global, $data, undefined) {

    
  $data.Entity.extend('Graph.Extensions.Service.ExtensionAttribute', {
     'Url': { 'type':'Edm.String' }
  });

  $data.Entity.extend('Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject', {
     'objectType': { 'type':'Edm.String' },
     'objectId': { 'key':true,'type':'Edm.String','nullable':false,'required':true },
     'manager': { 'type':'Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject','inverseProperty':'$$unbound' },
     'directReports': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject','inverseProperty':'$$unbound' },
     'members': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject','inverseProperty':'$$unbound' },
     'memberOf': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject','inverseProperty':'$$unbound' },
      'checkMemberGroups': { type: $data.ServiceAction, returnType: $data.Queryable, elementType: 'Edm.String', IsBindable: true, params: [{ name: 'groupIds', type: 'Collection(Edm.String)' }] },
      'getMemberGroups': { type: $data.ServiceAction, returnType: $data.Queryable, elementType: 'Edm.String', IsBindable: true, params: [{ name: 'securityEnabledOnly', type: 'Edm.Boolean' }] }
  });

  Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject.extend('Microsoft.WindowsAzure.ActiveDirectory.Application', {
     'appId': { 'type':'Edm.Guid' },
     'availableToOtherTenants': { 'type':'Edm.Boolean' },
     'displayName': { 'type':'Edm.String' },
     'errorUrl': { 'type':'Edm.String' },
     'homepage': { 'type':'Edm.String' },
     'identifierUris': { 'type':'Array','elementType':'Edm.String','nullable':false,'required':true },
     'keyCredentials': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.KeyCredential','nullable':false,'required':true },
     'logoutUrl': { 'type':'Edm.String' },
     'passwordCredentials': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.PasswordCredential','nullable':false,'required':true },
     'publicClient': { 'type':'Edm.Boolean' },
     'replyUrls': { 'type':'Array','elementType':'Edm.String','nullable':false,'required':true },
     'samlMetadataUrl': { 'type':'Edm.String' }
  });

  $data.Entity.extend('Microsoft.WindowsAzure.ActiveDirectory.KeyCredential', {
     'customKeyIdentifier': { 'type':'Edm.Binary' },
     'endDate': { 'type':'Edm.DateTime' },
     'keyId': { 'type':'Edm.Guid' },
     'startDate': { 'type':'Edm.DateTime' },
     'type': { 'type':'Edm.String' },
     'usage': { 'type':'Edm.String' },
     'value': { 'type':'Edm.Binary' }
  });

  $data.Entity.extend('Microsoft.WindowsAzure.ActiveDirectory.PasswordCredential', {
     'customKeyIdentifier': { 'type':'Edm.Binary' },
     'endDate': { 'type':'Edm.DateTime' },
     'keyId': { 'type':'Edm.Guid' },
     'startDate': { 'type':'Edm.DateTime' },
     'value': { 'type':'Edm.String' }
  });

  Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject.extend('Microsoft.WindowsAzure.ActiveDirectory.Contact', {
     'city': { 'type':'Edm.String' },
     'country': { 'type':'Edm.String' },
     'department': { 'type':'Edm.String' },
     'dirSyncEnabled': { 'type':'Edm.Boolean' },
     'displayName': { 'type':'Edm.String' },
     'facsimileTelephoneNumber': { 'type':'Edm.String' },
     'givenName': { 'type':'Edm.String' },
     'jobTitle': { 'type':'Edm.String' },
     'lastDirSyncTime': { 'type':'Edm.DateTime' },
     'mail': { 'type':'Edm.String' },
     'mailNickname': { 'type':'Edm.String' },
     'mobile': { 'type':'Edm.String' },
     'physicalDeliveryOfficeName': { 'type':'Edm.String' },
     'postalCode': { 'type':'Edm.String' },
     'provisioningErrors': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.ProvisioningError','nullable':false,'required':true },
     'proxyAddresses': { 'type':'Array','elementType':'Edm.String','nullable':false,'required':true },
     'state': { 'type':'Edm.String' },
     'streetAddress': { 'type':'Edm.String' },
     'surname': { 'type':'Edm.String' },
     'telephoneNumber': { 'type':'Edm.String' }
  });

  $data.Entity.extend('Microsoft.WindowsAzure.ActiveDirectory.ProvisioningError', {
     'errorDetail': { 'type':'Edm.String' },
     'resolved': { 'type':'Edm.Boolean' },
     'service': { 'type':'Edm.String' },
     'timestamp': { 'type':'Edm.DateTime' }
  });

  Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject.extend('Microsoft.WindowsAzure.ActiveDirectory.Device', {
     'accountEnabled': { 'type':'Edm.Boolean' },
     'alternativeSecurityIds': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.AlternativeSecurityId','nullable':false,'required':true },
     'approximateLastLogonTimestamp': { 'type':'Edm.DateTime' },
     'deviceId': { 'type':'Edm.Guid' },
     'deviceObjectVersion': { 'type':'Edm.Int32' },
     'deviceOSType': { 'type':'Edm.String' },
     'deviceOSVersion': { 'type':'Edm.String' },
     'devicePhysicalIds': { 'type':'Array','elementType':'Edm.String','nullable':false,'required':true },
     'dirSyncEnabled': { 'type':'Edm.Boolean' },
     'displayName': { 'type':'Edm.String' },
     'lastDirSyncTime': { 'type':'Edm.DateTime' },
     'registeredOwners': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject','inverseProperty':'$$unbound' },
     'registeredUsers': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject','inverseProperty':'$$unbound' }
  });

  $data.Entity.extend('Microsoft.WindowsAzure.ActiveDirectory.AlternativeSecurityId', {
     'type': { 'type':'Edm.Int32' },
     'identityProvider': { 'type':'Edm.String' },
     'key': { 'type':'Edm.Binary' }
  });

  Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject.extend('Microsoft.WindowsAzure.ActiveDirectory.DirectoryLinkChange', {
     'associationType': { 'type':'Edm.String' },
     'sourceObjectId': { 'type':'Edm.String' },
     'sourceObjectType': { 'type':'Edm.String' },
     'sourceObjectUri': { 'type':'Edm.String' },
     'targetObjectId': { 'type':'Edm.String' },
     'targetObjectType': { 'type':'Edm.String' },
     'targetObjectUri': { 'type':'Edm.String' }
  });

  Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject.extend('Microsoft.WindowsAzure.ActiveDirectory.Group', {
     'description': { 'type':'Edm.String' },
     'dirSyncEnabled': { 'type':'Edm.Boolean' },
     'displayName': { 'type':'Edm.String' },
     'lastDirSyncTime': { 'type':'Edm.DateTime' },
     'mail': { 'type':'Edm.String' },
     'mailNickname': { 'type':'Edm.String' },
     'mailEnabled': { 'type':'Edm.Boolean' },
     'provisioningErrors': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.ProvisioningError','nullable':false,'required':true },
     'proxyAddresses': { 'type':'Array','elementType':'Edm.String','nullable':false,'required':true },
     'securityEnabled': { 'type':'Edm.Boolean' }
  });

  Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject.extend('Microsoft.WindowsAzure.ActiveDirectory.Role', {
     'description': { 'type':'Edm.String' },
     'displayName': { 'type':'Edm.String' },
     'isSystem': { 'type':'Edm.Boolean' },
     'roleDisabled': { 'type':'Edm.Boolean' }
  });

  Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject.extend('Microsoft.WindowsAzure.ActiveDirectory.RoleTemplate', {
     'description': { 'type':'Edm.String' },
     'displayName': { 'type':'Edm.String' }
  });

  Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject.extend('Microsoft.WindowsAzure.ActiveDirectory.ServicePrincipal', {
     'accountEnabled': { 'type':'Edm.Boolean' },
     'appId': { 'type':'Edm.Guid' },
     'displayName': { 'type':'Edm.String' },
     'errorUrl': { 'type':'Edm.String' },
     'homepage': { 'type':'Edm.String' },
     'keyCredentials': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.KeyCredential','nullable':false,'required':true },
     'logoutUrl': { 'type':'Edm.String' },
     'passwordCredentials': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.PasswordCredential','nullable':false,'required':true },
     'publisherName': { 'type':'Edm.String' },
     'replyUrls': { 'type':'Array','elementType':'Edm.String','nullable':false,'required':true },
     'samlMetadataUrl': { 'type':'Edm.String' },
     'servicePrincipalNames': { 'type':'Array','elementType':'Edm.String','nullable':false,'required':true },
     'tags': { 'type':'Array','elementType':'Edm.String','nullable':false,'required':true },
     'permissions': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.Permission','inverseProperty':'$$unbound' }
  });

  Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject.extend('Microsoft.WindowsAzure.ActiveDirectory.TenantDetail', {
     'assignedPlans': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.AssignedPlan','nullable':false,'required':true },
     'city': { 'type':'Edm.String' },
     'companyLastDirSyncTime': { 'type':'Edm.DateTime' },
     'country': { 'type':'Edm.String' },
     'countryLetterCode': { 'type':'Edm.String' },
     'dirSyncEnabled': { 'type':'Edm.Boolean' },
     'displayName': { 'type':'Edm.String' },
     'marketingNotificationEmails': { 'type':'Array','elementType':'Edm.String','nullable':false,'required':true },
     'postalCode': { 'type':'Edm.String' },
     'preferredLanguage': { 'type':'Edm.String' },
     'provisionedPlans': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.ProvisionedPlan','nullable':false,'required':true },
     'provisioningErrors': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.ProvisioningError','nullable':false,'required':true },
     'state': { 'type':'Edm.String' },
     'street': { 'type':'Edm.String' },
     'technicalNotificationMails': { 'type':'Array','elementType':'Edm.String','nullable':false,'required':true },
     'telephoneNumber': { 'type':'Edm.String' },
     'tenantType': { 'type':'Edm.String' },
     'verifiedDomains': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.VerifiedDomain','nullable':false,'required':true }
  });

  $data.Entity.extend('Microsoft.WindowsAzure.ActiveDirectory.AssignedPlan', {
     'assignedTimestamp': { 'type':'Edm.DateTime' },
     'capabilityStatus': { 'type':'Edm.String' },
     'service': { 'type':'Edm.String' },
     'servicePlanId': { 'type':'Edm.Guid' }
  });

  $data.Entity.extend('Microsoft.WindowsAzure.ActiveDirectory.ProvisionedPlan', {
     'capabilityStatus': { 'type':'Edm.String' },
     'provisioningStatus': { 'type':'Edm.String' },
     'service': { 'type':'Edm.String' }
  });

  $data.Entity.extend('Microsoft.WindowsAzure.ActiveDirectory.VerifiedDomain', {
     'capabilities': { 'type':'Edm.String' },
     'default': { 'type':'Edm.Boolean' },
     'id': { 'type':'Edm.String' },
     'initial': { 'type':'Edm.Boolean' },
     'name': { 'type':'Edm.String' },
     'type': { 'type':'Edm.String' }
  });

  Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject.extend('Microsoft.WindowsAzure.ActiveDirectory.User', {
     'accountEnabled': { 'type':'Edm.Boolean' },
     'assignedLicenses': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.AssignedLicense','nullable':false,'required':true },
     'assignedPlans': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.AssignedPlan','nullable':false,'required':true },
     'city': { 'type':'Edm.String' },
     'country': { 'type':'Edm.String' },
     'department': { 'type':'Edm.String' },
     'dirSyncEnabled': { 'type':'Edm.Boolean' },
     'displayName': { 'type':'Edm.String' },
     'facsimileTelephoneNumber': { 'type':'Edm.String' },
     'givenName': { 'type':'Edm.String' },
     'jobTitle': { 'type':'Edm.String' },
     'lastDirSyncTime': { 'type':'Edm.DateTime' },
     'mail': { 'type':'Edm.String' },
     'mailNickname': { 'type':'Edm.String' },
     'mobile': { 'type':'Edm.String' },
     'otherMails': { 'type':'Array','elementType':'Edm.String','nullable':false,'required':true },
     'passwordPolicies': { 'type':'Edm.String' },
     'passwordProfile': { 'type':'Microsoft.WindowsAzure.ActiveDirectory.PasswordProfile' },
     'physicalDeliveryOfficeName': { 'type':'Edm.String' },
     'postalCode': { 'type':'Edm.String' },
     'preferredLanguage': { 'type':'Edm.String' },
     'provisionedPlans': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.ProvisionedPlan','nullable':false,'required':true },
     'provisioningErrors': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.ProvisioningError','nullable':false,'required':true },
     'proxyAddresses': { 'type':'Array','elementType':'Edm.String','nullable':false,'required':true },
     'state': { 'type':'Edm.String' },
     'streetAddress': { 'type':'Edm.String' },
     'surname': { 'type':'Edm.String' },
     'telephoneNumber': { 'type':'Edm.String' },
     'usageLocation': { 'type':'Edm.String' },
     'userPrincipalName': { 'type':'Edm.String' },
     'permissions': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.Permission','inverseProperty':'$$unbound' },
     'registeredDevices': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject','inverseProperty':'$$unbound' },
     'ownedDevices': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject','inverseProperty':'$$unbound' }
  });

  $data.Entity.extend('Microsoft.WindowsAzure.ActiveDirectory.AssignedLicense', {
     'disabledPlans': { 'type':'Array','elementType':'Edm.Guid','nullable':false,'required':true },
     'skuId': { 'type':'Edm.Guid' }
  });

  $data.Entity.extend('Microsoft.WindowsAzure.ActiveDirectory.PasswordProfile', {
     'password': { 'type':'Edm.String' },
     'forceChangePasswordNextLogin': { 'type':'Edm.Boolean' }
  });

  $data.Entity.extend('Microsoft.WindowsAzure.ActiveDirectory.Permission', {
     'clientId': { 'type':'Edm.String' },
     'consentType': { 'type':'Edm.String' },
     'expiryTime': { 'type':'Edm.DateTime' },
     'objectId': { 'key':true,'type':'Edm.String','nullable':false,'required':true },
     'principalId': { 'type':'Edm.String' },
     'resourceId': { 'type':'Edm.String' },
     'scope': { 'type':'Edm.String' },
     'startTime': { 'type':'Edm.DateTime' }
  });

  $data.Entity.extend('Microsoft.WindowsAzure.ActiveDirectory.SubscribedSku', {
     'capabilityStatus': { 'type':'Edm.String' },
     'consumedUnits': { 'type':'Edm.Int32' },
     'objectId': { 'key':true,'type':'Edm.String','nullable':false,'required':true },
     'prepaidUnits': { 'type':'Microsoft.WindowsAzure.ActiveDirectory.LicenseUnitsDetail' },
     'servicePlans': { 'type':'Array','elementType':'Microsoft.WindowsAzure.ActiveDirectory.ServicePlanInfo','nullable':false,'required':true },
     'skuId': { 'type':'Edm.Guid' },
     'skuPartNumber': { 'type':'Edm.String' }
  });

  $data.Entity.extend('Microsoft.WindowsAzure.ActiveDirectory.LicenseUnitsDetail', {
     'enabled': { 'type':'Edm.Int32' },
     'suspended': { 'type':'Edm.Int32' },
     'warning': { 'type':'Edm.Int32' }
  });

  $data.Entity.extend('Microsoft.WindowsAzure.ActiveDirectory.ServicePlanInfo', {
     'servicePlanId': { 'type':'Edm.Guid' },
     'servicePlanName': { 'type':'Edm.String' }
  });

  $data.EntityContext.extend('Graph.Extensions.Service.DataSource', {
     'GetExtension': { type: $data.ServiceOperation, returnType: 'Graph.Extensions.Service.ExtensionAttribute', params: [{ name: 'className', type: 'Edm.String' }, { name: 'attribute', type: 'Edm.String' }, { name: 'extendedItemId', type: 'Edm.String' }, { name: 'originalurl', type: 'Edm.String' }] }
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(Graph.Extensions.Service.DataSource);
    $data.EntityContext.extend('Microsoft.WindowsAzure.ActiveDirectory.DirectoryDataService', {
     'users': { type: $data.EntitySet, elementType: Microsoft.WindowsAzure.ActiveDirectory.User},
     'applications': { type: $data.EntitySet, elementType: Microsoft.WindowsAzure.ActiveDirectory.Application},
     'contacts': { type: $data.EntitySet, elementType: Microsoft.WindowsAzure.ActiveDirectory.Contact},
     'groups': { type: $data.EntitySet, elementType: Microsoft.WindowsAzure.ActiveDirectory.Group},
     'roles': { type: $data.EntitySet, elementType: Microsoft.WindowsAzure.ActiveDirectory.Role},
     'servicePrincipals': { type: $data.EntitySet, elementType: Microsoft.WindowsAzure.ActiveDirectory.ServicePrincipal},
     'tenantDetails': { type: $data.EntitySet, elementType: Microsoft.WindowsAzure.ActiveDirectory.TenantDetail},
     'devices': { type: $data.EntitySet, elementType: Microsoft.WindowsAzure.ActiveDirectory.Device},
     'subscribedSkus': { type: $data.EntitySet, elementType: Microsoft.WindowsAzure.ActiveDirectory.SubscribedSku},
     'permissions': { type: $data.EntitySet, elementType: Microsoft.WindowsAzure.ActiveDirectory.Permission},
     'directoryObjects': { type: $data.EntitySet, elementType: Microsoft.WindowsAzure.ActiveDirectory.DirectoryObject},
     'isMemberOf': { type: $data.ServiceOperation, returnType: 'Edm.Boolean', params: [{ name: 'groupId', type: 'Edm.String' }, { name: 'memberId', type: 'Edm.String' }] }
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(Microsoft.WindowsAzure.ActiveDirectory.DirectoryDataService);
  
      
})(window, $data);
      
    